/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthManagerTeamRouteImport } from './routes/_auth/manager/team'
import { Route as AuthManagerDashboardRouteImport } from './routes/_auth/manager/dashboard'
import { Route as AuthManagerCalendarRouteImport } from './routes/_auth/manager/calendar'
import { Route as AuthHrRecordsRouteImport } from './routes/_auth/hr/records'
import { Route as AuthHrPoliciesRouteImport } from './routes/_auth/hr/policies'
import { Route as AuthHrEmployeesRouteImport } from './routes/_auth/hr/employees'
import { Route as AuthHrDashboardRouteImport } from './routes/_auth/hr/dashboard'
import { Route as AuthHrCalendarRouteImport } from './routes/_auth/hr/calendar'
import { Route as AuthEmployeeHistoryRouteImport } from './routes/_auth/employee/history'
import { Route as AuthEmployeeDashboardRouteImport } from './routes/_auth/employee/dashboard'
import { Route as AuthManagerApproveIdRouteImport } from './routes/_auth/manager/approve.$id'
import { Route as AuthHrEmployeesIdRouteImport } from './routes/_auth/hr/employees.$id'
import { Route as AuthEmployeeRequestNewRouteImport } from './routes/_auth/employee/request.new'
import { Route as AuthEmployeeRequestIdRouteImport } from './routes/_auth/employee/request.$id'
import { Route as AuthEmployeeRequestIdEditRouteImport } from './routes/_auth/employee/request.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthManagerTeamRoute = AuthManagerTeamRouteImport.update({
  id: '/manager/team',
  path: '/manager/team',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerDashboardRoute = AuthManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerCalendarRoute = AuthManagerCalendarRouteImport.update({
  id: '/manager/calendar',
  path: '/manager/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrRecordsRoute = AuthHrRecordsRouteImport.update({
  id: '/hr/records',
  path: '/hr/records',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrPoliciesRoute = AuthHrPoliciesRouteImport.update({
  id: '/hr/policies',
  path: '/hr/policies',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrEmployeesRoute = AuthHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrDashboardRoute = AuthHrDashboardRouteImport.update({
  id: '/hr/dashboard',
  path: '/hr/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrCalendarRoute = AuthHrCalendarRouteImport.update({
  id: '/hr/calendar',
  path: '/hr/calendar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeHistoryRoute = AuthEmployeeHistoryRouteImport.update({
  id: '/employee/history',
  path: '/employee/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeDashboardRoute = AuthEmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthManagerApproveIdRoute = AuthManagerApproveIdRouteImport.update({
  id: '/manager/approve/$id',
  path: '/manager/approve/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHrEmployeesIdRoute = AuthHrEmployeesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthHrEmployeesRoute,
} as any)
const AuthEmployeeRequestNewRoute = AuthEmployeeRequestNewRouteImport.update({
  id: '/employee/request/new',
  path: '/employee/request/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeRequestIdRoute = AuthEmployeeRequestIdRouteImport.update({
  id: '/employee/request/$id',
  path: '/employee/request/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmployeeRequestIdEditRoute =
  AuthEmployeeRequestIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthEmployeeRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/employee/dashboard': typeof AuthEmployeeDashboardRoute
  '/employee/history': typeof AuthEmployeeHistoryRoute
  '/hr/calendar': typeof AuthHrCalendarRoute
  '/hr/dashboard': typeof AuthHrDashboardRoute
  '/hr/employees': typeof AuthHrEmployeesRouteWithChildren
  '/hr/policies': typeof AuthHrPoliciesRoute
  '/hr/records': typeof AuthHrRecordsRoute
  '/manager/calendar': typeof AuthManagerCalendarRoute
  '/manager/dashboard': typeof AuthManagerDashboardRoute
  '/manager/team': typeof AuthManagerTeamRoute
  '/employee/request/$id': typeof AuthEmployeeRequestIdRouteWithChildren
  '/employee/request/new': typeof AuthEmployeeRequestNewRoute
  '/hr/employees/$id': typeof AuthHrEmployeesIdRoute
  '/manager/approve/$id': typeof AuthManagerApproveIdRoute
  '/employee/request/$id/edit': typeof AuthEmployeeRequestIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/employee/dashboard': typeof AuthEmployeeDashboardRoute
  '/employee/history': typeof AuthEmployeeHistoryRoute
  '/hr/calendar': typeof AuthHrCalendarRoute
  '/hr/dashboard': typeof AuthHrDashboardRoute
  '/hr/employees': typeof AuthHrEmployeesRouteWithChildren
  '/hr/policies': typeof AuthHrPoliciesRoute
  '/hr/records': typeof AuthHrRecordsRoute
  '/manager/calendar': typeof AuthManagerCalendarRoute
  '/manager/dashboard': typeof AuthManagerDashboardRoute
  '/manager/team': typeof AuthManagerTeamRoute
  '/employee/request/$id': typeof AuthEmployeeRequestIdRouteWithChildren
  '/employee/request/new': typeof AuthEmployeeRequestNewRoute
  '/hr/employees/$id': typeof AuthHrEmployeesIdRoute
  '/manager/approve/$id': typeof AuthManagerApproveIdRoute
  '/employee/request/$id/edit': typeof AuthEmployeeRequestIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/employee/dashboard': typeof AuthEmployeeDashboardRoute
  '/_auth/employee/history': typeof AuthEmployeeHistoryRoute
  '/_auth/hr/calendar': typeof AuthHrCalendarRoute
  '/_auth/hr/dashboard': typeof AuthHrDashboardRoute
  '/_auth/hr/employees': typeof AuthHrEmployeesRouteWithChildren
  '/_auth/hr/policies': typeof AuthHrPoliciesRoute
  '/_auth/hr/records': typeof AuthHrRecordsRoute
  '/_auth/manager/calendar': typeof AuthManagerCalendarRoute
  '/_auth/manager/dashboard': typeof AuthManagerDashboardRoute
  '/_auth/manager/team': typeof AuthManagerTeamRoute
  '/_auth/employee/request/$id': typeof AuthEmployeeRequestIdRouteWithChildren
  '/_auth/employee/request/new': typeof AuthEmployeeRequestNewRoute
  '/_auth/hr/employees/$id': typeof AuthHrEmployeesIdRoute
  '/_auth/manager/approve/$id': typeof AuthManagerApproveIdRoute
  '/_auth/employee/request/$id/edit': typeof AuthEmployeeRequestIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/employee/dashboard'
    | '/employee/history'
    | '/hr/calendar'
    | '/hr/dashboard'
    | '/hr/employees'
    | '/hr/policies'
    | '/hr/records'
    | '/manager/calendar'
    | '/manager/dashboard'
    | '/manager/team'
    | '/employee/request/$id'
    | '/employee/request/new'
    | '/hr/employees/$id'
    | '/manager/approve/$id'
    | '/employee/request/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/employee/dashboard'
    | '/employee/history'
    | '/hr/calendar'
    | '/hr/dashboard'
    | '/hr/employees'
    | '/hr/policies'
    | '/hr/records'
    | '/manager/calendar'
    | '/manager/dashboard'
    | '/manager/team'
    | '/employee/request/$id'
    | '/employee/request/new'
    | '/hr/employees/$id'
    | '/manager/approve/$id'
    | '/employee/request/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/employee/dashboard'
    | '/_auth/employee/history'
    | '/_auth/hr/calendar'
    | '/_auth/hr/dashboard'
    | '/_auth/hr/employees'
    | '/_auth/hr/policies'
    | '/_auth/hr/records'
    | '/_auth/manager/calendar'
    | '/_auth/manager/dashboard'
    | '/_auth/manager/team'
    | '/_auth/employee/request/$id'
    | '/_auth/employee/request/new'
    | '/_auth/hr/employees/$id'
    | '/_auth/manager/approve/$id'
    | '/_auth/employee/request/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/manager/team': {
      id: '/_auth/manager/team'
      path: '/manager/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof AuthManagerTeamRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manager/dashboard': {
      id: '/_auth/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof AuthManagerDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manager/calendar': {
      id: '/_auth/manager/calendar'
      path: '/manager/calendar'
      fullPath: '/manager/calendar'
      preLoaderRoute: typeof AuthManagerCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/records': {
      id: '/_auth/hr/records'
      path: '/hr/records'
      fullPath: '/hr/records'
      preLoaderRoute: typeof AuthHrRecordsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/policies': {
      id: '/_auth/hr/policies'
      path: '/hr/policies'
      fullPath: '/hr/policies'
      preLoaderRoute: typeof AuthHrPoliciesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/employees': {
      id: '/_auth/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthHrEmployeesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/dashboard': {
      id: '/_auth/hr/dashboard'
      path: '/hr/dashboard'
      fullPath: '/hr/dashboard'
      preLoaderRoute: typeof AuthHrDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/calendar': {
      id: '/_auth/hr/calendar'
      path: '/hr/calendar'
      fullPath: '/hr/calendar'
      preLoaderRoute: typeof AuthHrCalendarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee/history': {
      id: '/_auth/employee/history'
      path: '/employee/history'
      fullPath: '/employee/history'
      preLoaderRoute: typeof AuthEmployeeHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee/dashboard': {
      id: '/_auth/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof AuthEmployeeDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/manager/approve/$id': {
      id: '/_auth/manager/approve/$id'
      path: '/manager/approve/$id'
      fullPath: '/manager/approve/$id'
      preLoaderRoute: typeof AuthManagerApproveIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/hr/employees/$id': {
      id: '/_auth/hr/employees/$id'
      path: '/$id'
      fullPath: '/hr/employees/$id'
      preLoaderRoute: typeof AuthHrEmployeesIdRouteImport
      parentRoute: typeof AuthHrEmployeesRoute
    }
    '/_auth/employee/request/new': {
      id: '/_auth/employee/request/new'
      path: '/employee/request/new'
      fullPath: '/employee/request/new'
      preLoaderRoute: typeof AuthEmployeeRequestNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee/request/$id': {
      id: '/_auth/employee/request/$id'
      path: '/employee/request/$id'
      fullPath: '/employee/request/$id'
      preLoaderRoute: typeof AuthEmployeeRequestIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/employee/request/$id/edit': {
      id: '/_auth/employee/request/$id/edit'
      path: '/edit'
      fullPath: '/employee/request/$id/edit'
      preLoaderRoute: typeof AuthEmployeeRequestIdEditRouteImport
      parentRoute: typeof AuthEmployeeRequestIdRoute
    }
  }
}

interface AuthHrEmployeesRouteChildren {
  AuthHrEmployeesIdRoute: typeof AuthHrEmployeesIdRoute
}

const AuthHrEmployeesRouteChildren: AuthHrEmployeesRouteChildren = {
  AuthHrEmployeesIdRoute: AuthHrEmployeesIdRoute,
}

const AuthHrEmployeesRouteWithChildren = AuthHrEmployeesRoute._addFileChildren(
  AuthHrEmployeesRouteChildren,
)

interface AuthEmployeeRequestIdRouteChildren {
  AuthEmployeeRequestIdEditRoute: typeof AuthEmployeeRequestIdEditRoute
}

const AuthEmployeeRequestIdRouteChildren: AuthEmployeeRequestIdRouteChildren = {
  AuthEmployeeRequestIdEditRoute: AuthEmployeeRequestIdEditRoute,
}

const AuthEmployeeRequestIdRouteWithChildren =
  AuthEmployeeRequestIdRoute._addFileChildren(
    AuthEmployeeRequestIdRouteChildren,
  )

interface AuthRouteChildren {
  AuthEmployeeDashboardRoute: typeof AuthEmployeeDashboardRoute
  AuthEmployeeHistoryRoute: typeof AuthEmployeeHistoryRoute
  AuthHrCalendarRoute: typeof AuthHrCalendarRoute
  AuthHrDashboardRoute: typeof AuthHrDashboardRoute
  AuthHrEmployeesRoute: typeof AuthHrEmployeesRouteWithChildren
  AuthHrPoliciesRoute: typeof AuthHrPoliciesRoute
  AuthHrRecordsRoute: typeof AuthHrRecordsRoute
  AuthManagerCalendarRoute: typeof AuthManagerCalendarRoute
  AuthManagerDashboardRoute: typeof AuthManagerDashboardRoute
  AuthManagerTeamRoute: typeof AuthManagerTeamRoute
  AuthEmployeeRequestIdRoute: typeof AuthEmployeeRequestIdRouteWithChildren
  AuthEmployeeRequestNewRoute: typeof AuthEmployeeRequestNewRoute
  AuthManagerApproveIdRoute: typeof AuthManagerApproveIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEmployeeDashboardRoute: AuthEmployeeDashboardRoute,
  AuthEmployeeHistoryRoute: AuthEmployeeHistoryRoute,
  AuthHrCalendarRoute: AuthHrCalendarRoute,
  AuthHrDashboardRoute: AuthHrDashboardRoute,
  AuthHrEmployeesRoute: AuthHrEmployeesRouteWithChildren,
  AuthHrPoliciesRoute: AuthHrPoliciesRoute,
  AuthHrRecordsRoute: AuthHrRecordsRoute,
  AuthManagerCalendarRoute: AuthManagerCalendarRoute,
  AuthManagerDashboardRoute: AuthManagerDashboardRoute,
  AuthManagerTeamRoute: AuthManagerTeamRoute,
  AuthEmployeeRequestIdRoute: AuthEmployeeRequestIdRouteWithChildren,
  AuthEmployeeRequestNewRoute: AuthEmployeeRequestNewRoute,
  AuthManagerApproveIdRoute: AuthManagerApproveIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
